[package]
name = "tuono_lib"
version = "0.0.1"
edition = "2021"
authors = ["V. Ageno <valerioageno@yahoo.it>"]

[lib]
name = "tuono_lib"
path = "src/lib.rs"

[dependencies]
ssr_rs = "0.5.1"
axum = "0.7.5"
serde = { version = "1.0.202", features = ["derive"] }
erased-serde = "0.4.5"
serde_json = "1.0"

