[package]
name = "tuono_lib"
version = "0.0.1"
edition = "2021"
authors = ["V. Ageno <valerioageno@yahoo.it>"]

[lib]
name = "tuono_lib"
path = "src/lib.rs"

[dependencies]
ssr_rs = "0.5.1"
axum = "0.7.5"
tuono_lib_macros = { path = "../tuono_lib_macros"}
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0"

