[package]
name = "axum_bundler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
glob = "0.3.1"

fastmurmur3 = "0.2.0"

