[package]
name = "tuono_lib_macros"
version = "0.0.1"
edition = "2021"

[lib]
crate_type = ["proc-macro"]
proc-marco = true

[dependencies]
syn = { version = "1.0.59", features = ["full"] }
quote = "1.0"
